package nusynapxe.tools;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import nusynapxe.domain.IdentityType;
import nusynapxe.domain.Patient;
import nusynapxe.domain.Sex;
import nusynapxe.persistence.PatientRepository;

/** Creates the representative patient directory used by the local demo dataset. */
final class DemoDataPatientSeeder {
  private DemoDataPatientSeeder() {
    throw new AssertionError("Utility class");
  }

  static List<Patient> seed(PatientRepository repository) throws SQLException {
    List<Patient> patients = new ArrayList<>();
    for (Patient requestedPatient : requestedPatients()) {
      patients.add(repository.create(requestedPatient));
    }
    return List.copyOf(patients);
  }

  private static List<Patient> requestedPatients() {
    return List.of(
        new Patient(
            0,
            IdentityType.NRIC,
            "S1234567D",
            "SG",
            "Aisha",
            "Rahman",
            "1991-04-12",
            Sex.FEMALE,
            "65",
            "81234567",
            "aisha.rahman@example.test",
            "12 Demo Avenue",
            165.0,
            60.0,
            true),
        new Patient(
            0,
            IdentityType.FIN,
            "G2345678N",
            "SG",
            "Benjamin",
            "Tan",
            "1985-09-23",
            Sex.MALE,
            "65",
            "82345678",
            "benjamin.tan@example.test",
            "48 Showcase Road",
            178.0,
            74.5,
            true),
        new Patient(
            0,
            IdentityType.PASSPORT,
            "GB7K29M4",
            "GB",
            "Chloe",
            "Morgan",
            "1998-02-18",
            Sex.FEMALE,
            "44",
            "77009001",
            "chloe.morgan@example.test",
            "7 Orchard Walk",
            171.0,
            63.2,
            true),
        new Patient(
            0,
            IdentityType.PASSPORT,
            "AU4P82Q1",
            "AU",
            "Daniel",
            "Wong",
            "1977-11-05",
            Sex.MALE,
            "61",
            "412345678",
            "daniel.wong@example.test",
            "31 Riverside Crescent",
            182.0,
            86.0,
            true),
        new Patient(
            0,
            IdentityType.OTHER,
            "SHOWCASE-05",
            "SG",
            "Elena",
            "Lim",
            "2002-06-30",
            Sex.FEMALE,
            "65",
            "83456789",
            "elena.lim@example.test",
            "5 Gallery Lane",
            160.0,
            52.8,
            true),
        new Patient(
            0,
            IdentityType.NRIC,
            "T7654321H",
            "SG",
            "Farid",
            "Ismail",
            "1969-01-27",
            Sex.MALE,
            "65",
            "84567890",
            "farid.ismail@example.test",
            "90 Heritage Street",
            174.0,
            79.0,
            true),
        new Patient(
            0,
            IdentityType.OTHER,
            "SHOWCASE-07",
            "SG",
            "Grace",
            "Chong",
            "1993-08-16",
            Sex.FEMALE,
            "65",
            "85678901",
            "grace.chong@example.test",
            "18 Harbour View",
            168.0,
            58.0,
            true),
        new Patient(
            0,
            IdentityType.OTHER,
            "SHOWCASE-08",
            "SG",
            "Hassan",
            "Khan",
            "1988-03-09",
            Sex.MALE,
            "65",
            "86789012",
            "hassan.khan@example.test",
            "22 Hilltop Drive",
            176.0,
            81.0,
            true),
        new Patient(
            0,
            IdentityType.OTHER,
            "SHOWCASE-09",
            "SG",
            "Irene",
            "Goh",
            "1975-12-21",
            Sex.FEMALE,
            "65",
            "87890123",
            "irene.goh@example.test",
            "6 Maple Street",
            162.0,
            67.0,
            true),
        new Patient(
            0,
            IdentityType.OTHER,
            "SHOWCASE-10",
            "SG",
            "Jared",
            "Lee",
            "2000-05-14",
            Sex.MALE,
            "65",
            "88901234",
            "jared.lee@example.test",
            "44 Lakeside Walk",
            181.0,
            76.0,
            true),
        new Patient(
            0,
            IdentityType.OTHER,
            "SHOWCASE-11",
            "SG",
            "Kavita",
            "Nair",
            "1990-10-03",
            Sex.FEMALE,
            "65",
            "89012345",
            "kavita.nair@example.test",
            "9 Palm Grove",
            158.0,
            55.0,
            true),
        new Patient(
            0,
            IdentityType.OTHER,
            "SHOWCASE-12",
            "SG",
            "Leon",
            "Ong",
            "1982-07-28",
            Sex.MALE,
            "65",
            "80123456",
            "leon.ong@example.test",
            "73 Garden Terrace",
            179.0,
            83.0,
            true),
        new Patient(
            0,
            IdentityType.OTHER,
            "SHOWCASE-13",
            "SG",
            "Mei",
            "Soh",
            "1996-01-19",
            Sex.FEMALE,
            "65",
            "81235670",
            "mei.soh@example.test",
            "15 Sunset Avenue",
            164.0,
            57.0,
            true),
        new Patient(
            0,
            IdentityType.OTHER,
            "SHOWCASE-14",
            "SG",
            "Nabil",
            "Rahim",
            "1970-09-07",
            Sex.MALE,
            "65",
            "82356781",
            "nabil.rahim@example.test",
            "28 Heritage Lane",
            173.0,
            78.0,
            true),
        new Patient(
            0,
            IdentityType.OTHER,
            "SHOWCASE-15",
            "SG",
            "Olivia",
            "Teo",
            "2004-04-25",
            Sex.FEMALE,
            "65",
            "83467892",
            "olivia.teo@example.test",
            "3 Studio Crescent",
            169.0,
            61.0,
            true),
        new Patient(
            0,
            IdentityType.OTHER,
            "SHOWCASE-16",
            "SG",
            "Pavel",
            "Ivanov",
            "1987-06-11",
            Sex.MALE,
            "65",
            "84578903",
            "pavel.ivanov@example.test",
            "52 Riverbank Road",
            184.0,
            88.0,
            true),
        new Patient(
            0,
            IdentityType.OTHER,
            "SHOWCASE-17",
            "SG",
            "Sara",
            "Yeo",
            "1999-11-02",
            Sex.FEMALE,
            "65",
            "85689014",
            "sara.yeo@example.test",
            "11 Orchard Rise",
            161.0,
            54.0,
            false),
        new Patient(
            0,
            IdentityType.OTHER,
            "SHOWCASE-18",
            "SG",
            "Tariq",
            "Halim",
            "1964-02-13",
            Sex.MALE,
            "65",
            "86790125",
            "tariq.halim@example.test",
            "87 Heritage Street",
            177.0,
            82.0,
            false));
  }
}
